spring.application.name=NaukriBuddy
spring.datasource.url=jdbc:mysql://localhost:3306/naukri_buddy_db
spring.datasource.username=root
spring.datasource.password=@CoolChetan194
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
